apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-price-predictor
  template:
    metadata:
      labels:
        app: flight-price-predictor
    spec:
      containers:
      - name: flight-price-predictor
        image: docker.io/bsshewale/flight-price-predictor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
