apiVersion: v1
kind: Service
metadata:
  name: flight-price-service
spec:
  selector:
    app: flight-price-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
